### ISSUE TITLE
wurflgo will hang on go1.3 build

### ISSUE THREAD

**Issue by Rick1125** [srinathgs/wurflgo#1]
wurflgo will hang on go1.3 when execute command go build wurfl.go <your file>.go
I've tried on my mac and ubuntu server.

**Comment by srinathgs** [comment]
@Rick1125 go build for this wurflgo takes a while to build. It mostly is a memory issue when go tries to build the source file. Please bump up RAM in the build machine and try it out again. also monitor memory utilisation when running go build

**Comment by srinathgs** [comment]
@Rick1125 closing this issue.
